### ISSUE TITLE
skins do not appear after initializing the control factory

### ISSUE THREAD

**Issue by volkanunsal** [razorberry/razor#1]
Hey Ash,

Here is a quick bug report for the issue I reported the other day. 

> Settings.setSkin(new PlasticStyleSheet(), new Glass());

This line does not add a defaultStylesheet to the factory. Hence the components appear naked.

**Comment by volkanunsal** [comment]
closing this issue. using setSize() on component solves the issue.

**Comment by razorberry** [comment]
closing
