### ISSUE TITLE
Dependecy

### ISSUE THREAD

**Issue by FrancisVarga** [razorberry/razor#2]
import com.degrafa.GeometryGroup;
import com.degrafa.IGeometry;

can u import it to your source or can you link it? i get errors by compiling...

**Comment by razorberry** [comment]
You can delete the razor/adapters/degrafa folder to solve this issue. I may remove this folder from the repo as it was experimental anyway.

**Comment by FrancisVarga** [comment]
thx okay i do it and work fine :)
