### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by wangchyz** [razorberry/razor#3]
very little code:
    public class MainView extends Container
    {
        public function MainView() 
        {
            Settings.setSkin(new PlasticStyleSheet(), new Glass()); 

```
        var helloBtn:Button = ControlFactory.create(Button) as Button;
        helloBtn.label = "I have a tooltip";
        helloBtn.tooltip = new TooltipData("This button has a tooltip");
        addChild(helloBtn);  
    }   
}
```

why button can't show skin?

**Comment by razorberry** [comment]
UNfortunately you need to set the size of the button before anything will show:

helloBtn.setSize(200,30);
