### ISSUE TITLE
hi razor,the control Accordion is likely unusable.

### ISSUE THREAD

**Issue by hzlijianjun** [razorberry/razor#4]
The control Accordion is likely unusable.I follow the API Document example of  Accordion.After running can't find thing in screen.

**Comment by chang7758y** [comment]
Razor tutorial is too little, a lot of difficult to solve

**Comment by razorberry** [comment]
Hi there!

Unfortunately, this project is no longer being maintained. I tried to provide enough examples in the sample program, but I simply don't have enough time to maintain the project.
I suspect it is being used very little, anyway :)
